package example.entities;
// Generated Jul 26, 2016 8:16:31 AM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmpDetailsView generated by hbm2java
 */
@Entity
@Table(name = "emp_details_view")
public class EmpDetailsView implements java.io.Serializable {

	private EmpDetailsViewId id;

	public EmpDetailsView() {
	}

	public EmpDetailsView(EmpDetailsViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeId", column = @Column(name = "employee_id", nullable = false)),
			@AttributeOverride(name = "jobId", column = @Column(name = "job_id", nullable = false, length = 10)),
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id")),
			@AttributeOverride(name = "departmentId", column = @Column(name = "department_id")),
			@AttributeOverride(name = "locationId", column = @Column(name = "location_id")),
			@AttributeOverride(name = "countryId", column = @Column(name = "country_id", nullable = false, length = 2)),
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name", length = 20)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name", nullable = false, length = 25)),
			@AttributeOverride(name = "salary", column = @Column(name = "salary", nullable = false, precision = 8)),
			@AttributeOverride(name = "commissionPct", column = @Column(name = "commission_pct", precision = 2)),
			@AttributeOverride(name = "departmentName", column = @Column(name = "department_name", nullable = false, length = 30)),
			@AttributeOverride(name = "jobTitle", column = @Column(name = "job_title", nullable = false, length = 35)),
			@AttributeOverride(name = "city", column = @Column(name = "city", nullable = false, length = 30)),
			@AttributeOverride(name = "stateProvince", column = @Column(name = "state_province", length = 25)),
			@AttributeOverride(name = "countryName", column = @Column(name = "country_name", length = 40)),
			@AttributeOverride(name = "regionName", column = @Column(name = "region_name", length = 25)) })
	public EmpDetailsViewId getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewId id) {
		this.id = id;
	}

}
